env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created a
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "DVmUB3H5Y9rK/xPXb6OdXgMrJDMo9LdOu+IlmkczT/OsLwirW1HaM58J4kccSaqEDYw05mhiX0MaS6DndRj2x0xYnUGfZWZ1Z8ELPVR6ysBlFyzC3/4NraOaIbD4OyI3Tk7pAU5AROUw3DMgVIU6Niv4YC/6FocBwP1SOfYewyM="

addons:
  coverity_scan:
    project:
      name: "Bartlby/bartlby-agent"
      description: "Bartlby Agent"
    notification_email: helmut@januschka.com
    build_command_prepend: make clean; ./configure --enable-nrpe --enable-ssl --prefix=$PWD/installation --with-user=travis
    build_command:   make -j4
    branch_pattern: coverity_scan


notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5b8a28a5122c15873c43
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false




before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libjson0-dev libjson0

before_script:
    # Compile PHP
    - ./travis/compile.sh

script: 
 - ./travis/build_check.sh

