# Makefile.in generated by automake 1.11.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008, 2009  Free Software Foundation,
# Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.






pkgdatadir = $(datadir)/bartlby-agent
pkgincludedir = $(includedir)/bartlby-agent
pkglibdir = $(libdir)/bartlby-agent
pkglibexecdir = $(libexecdir)/bartlby-agent
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
noinst_PROGRAMS = bartlby_agent$(EXEEXT) bartlby_agent_v2$(EXEEXT) \
	bartlby_cmd$(EXEEXT)
subdir = .
DIST_COMMON = $(am__configure_deps) $(dist_mysql_DATA) \
	$(dist_noinst_SCRIPTS) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in $(srcdir)/agent_sync.cfg.in \
	$(srcdir)/bartlby.cfg.in $(srcdir)/config.h.in \
	$(srcdir)/postinstall-pak.in $(srcdir)/preinstall-pak.in \
	$(top_srcdir)/configure COPYING INSTALL depcomp install-sh \
	missing
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES = bartlby.cfg postinstall-pak preinstall-pak \
	agent_sync.cfg
CONFIG_CLEAN_VPATH_FILES =
PROGRAMS = $(noinst_PROGRAMS)
am_bartlby_agent_OBJECTS = bartlby_agent-config.$(OBJEXT) \
	bartlby_agent-agent.$(OBJEXT)
bartlby_agent_OBJECTS = $(am_bartlby_agent_OBJECTS)
am__DEPENDENCIES_1 =
bartlby_agent_DEPENDENCIES = $(am__DEPENDENCIES_1)
bartlby_agent_LINK = $(CCLD) $(bartlby_agent_CFLAGS) $(CFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@
am_bartlby_agent_v2_OBJECTS = bartlby_agent_v2-config.$(OBJEXT) \
	bartlby_agent_v2-agent_v2.$(OBJEXT) \
	bartlby_agent_v2-global.$(OBJEXT)
bartlby_agent_v2_OBJECTS = $(am_bartlby_agent_v2_OBJECTS)
bartlby_agent_v2_DEPENDENCIES = $(am__DEPENDENCIES_1)
bartlby_agent_v2_LINK = $(CCLD) $(bartlby_agent_v2_CFLAGS) $(CFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@
am_bartlby_cmd_OBJECTS = bartlby_cmd-config.$(OBJEXT) \
	bartlby_cmd-global.$(OBJEXT) bartlby_cmd-cmd.$(OBJEXT)
bartlby_cmd_OBJECTS = $(am_bartlby_cmd_OBJECTS)
bartlby_cmd_DEPENDENCIES = $(am__DEPENDENCIES_1)
bartlby_cmd_LINK = $(CCLD) $(bartlby_cmd_CFLAGS) $(CFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@
SCRIPTS = $(dist_noinst_SCRIPTS)
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC    " $@;
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD  " $@;
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN   " $@;
SOURCES = $(bartlby_agent_SOURCES) $(bartlby_agent_v2_SOURCES) \
	$(bartlby_cmd_SOURCES)
DIST_SOURCES = $(bartlby_agent_SOURCES) $(bartlby_agent_v2_SOURCES) \
	$(bartlby_cmd_SOURCES)
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__installdirs = "$(DESTDIR)$(mysqldir)"
DATA = $(dist_mysql_DATA)
ETAGS = etags
CTAGS = ctags
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  { test ! -d "$(distdir)" \
    || { find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
         && rm -fr "$(distdir)"; }; }
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /storage/SF.NET/BARTLBY/GIT/bartlby-agent/missing --run aclocal-1.11
ALLOWEDIPS = 127.0.0.1
AMTAR = ${SHELL} /storage/SF.NET/BARTLBY/GIT/bartlby-agent/missing --run tar
AM_DEFAULT_VERBOSITY = 0
AUTOCONF = ${SHELL} /storage/SF.NET/BARTLBY/GIT/bartlby-agent/missing --run autoconf
AUTOHEADER = ${SHELL} /storage/SF.NET/BARTLBY/GIT/bartlby-agent/missing --run autoheader
AUTOMAKE = ${SHELL} /storage/SF.NET/BARTLBY/GIT/bartlby-agent/missing --run automake-1.11
AWK = gawk
BARTLBY_SYNC = http://localhost/bartlby-ui/
BARTLBY_SYNC_ARCH = i386
BARTLBY_SYNC_CLIENTNAME = bartlbydemo
BARTLBY_SYNC_PW = sync
BARTLBY_SYNC_USER = sync
BARTLBY_USER = bartlby
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPP = 
CPPFLAGS = 
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = 
EXEEXT = 
GREP = 
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_OPTIONS = -o bartlby
INSTALL_PATH = /usr/bin/install
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LDFLAGS = 
LIBOBJS =  ${LIBOBJDIR}lstat$U.o ${LIBOBJDIR}stat$U.o
LIBS = 
LOADLIMIT = 50
LTLIBOBJS =  ${LIBOBJDIR}lstat$U.lo ${LIBOBJDIR}stat$U.lo
MAKEINFO = ${SHELL} /storage/SF.NET/BARTLBY/GIT/bartlby-agent/missing --run makeinfo
MKDIR_P = /bin/mkdir -p
OBJEXT = o
OPENSSL_ADDON = 
OPENSSL_FLAG = 
OPENSSL_INCDIR = 
OPENSSL_LIBDIR = 
PACKAGE = bartlby-agent
PACKAGE_BUGREPORT = helmut@januschka.com
PACKAGE_NAME = bartlby-agent
PACKAGE_STRING = bartlby-agent 1.4.0
PACKAGE_TARNAME = bartlby-agent
PACKAGE_URL = 
PACKAGE_VERSION = 1.4.0
PATH_SEPARATOR = :
PLUGIN_DIR = /tmp/asd/plugins/
SET_MAKE = 
SHELL = /bin/sh
STRIP = 
VERSION = 1.4.0
abs_builddir = /storage/SF.NET/BARTLBY/GIT/bartlby-agent
abs_srcdir = /storage/SF.NET/BARTLBY/GIT/bartlby-agent
abs_top_builddir = /storage/SF.NET/BARTLBY/GIT/bartlby-agent
abs_top_srcdir = /storage/SF.NET/BARTLBY/GIT/bartlby-agent
ac_ct_CC = gcc
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
bindir = ${exec_prefix}/bin
build_alias = 
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host_alias = 
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /storage/SF.NET/BARTLBY/GIT/bartlby-agent/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /tmp/asd
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
AUTOMAKE_OPTIONS = subdir-objects foreign
ACLOCAL_AMFLAGS = ${ACLOCAL_FLAGS}
bartlby_agent_SOURCES = config.c  agent.c
bartlby_agent_LDADD = -ldl $(OPENSSL_FLAG) $(SNMP_FLAG)
bartlby_agent_CFLAGS = $(AM_CFLAGS)  $(NRPE_ADDON) $(SSL_ADDON)  $(SNMP_ADDON)
bartlby_agent_v2_SOURCES = config.c  agent_v2.c global.c
bartlby_agent_v2_LDADD = -ldl $(OPENSSL_FLAG) $(SNMP_FLAG)
bartlby_agent_v2_CFLAGS = $(AM_CFLAGS)  $(NRPE_ADDON) $(SSL_ADDON)  $(SNMP_ADDON)
bartlby_cmd_SOURCES = config.c  global.c cmd.c
bartlby_cmd_LDADD = -ldl $(OPENSSL_FLAG) $(SNMP_FLAG)
bartlby_cmd_CFLAGS = $(AM_CFLAGS)  $(NRPE_ADDON) $(SSL_ADDON)  $(SNMP_ADDON)
mysqldir = $(prefix)
dist_mysql_DATA = bartlby.cfg agent_sync.cfg agent_sync.sh passive_run.sample HOWTO.passive bartlby_agent bartlby_agent_v2 bartlby_cmd
dist_noinst_SCRIPTS = autogen.sh
all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .c .o .obj
am--refresh:
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

config.h: stamp-h1
	@if test ! -f $@; then \
	  rm -f stamp-h1; \
	  $(MAKE) $(AM_MAKEFLAGS) stamp-h1; \
	else :; fi

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1
bartlby.cfg: $(top_builddir)/config.status $(srcdir)/bartlby.cfg.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
postinstall-pak: $(top_builddir)/config.status $(srcdir)/postinstall-pak.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
preinstall-pak: $(top_builddir)/config.status $(srcdir)/preinstall-pak.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
agent_sync.cfg: $(top_builddir)/config.status $(srcdir)/agent_sync.cfg.in
	cd $(top_builddir) && $(SHELL) ./config.status $@

clean-noinstPROGRAMS:
	-test -z "$(noinst_PROGRAMS)" || rm -f $(noinst_PROGRAMS)
bartlby_agent$(EXEEXT): $(bartlby_agent_OBJECTS) $(bartlby_agent_DEPENDENCIES) 
	@rm -f bartlby_agent$(EXEEXT)
	$(AM_V_CCLD)$(bartlby_agent_LINK) $(bartlby_agent_OBJECTS) $(bartlby_agent_LDADD) $(LIBS)
bartlby_agent_v2$(EXEEXT): $(bartlby_agent_v2_OBJECTS) $(bartlby_agent_v2_DEPENDENCIES) 
	@rm -f bartlby_agent_v2$(EXEEXT)
	$(AM_V_CCLD)$(bartlby_agent_v2_LINK) $(bartlby_agent_v2_OBJECTS) $(bartlby_agent_v2_LDADD) $(LIBS)
bartlby_cmd$(EXEEXT): $(bartlby_cmd_OBJECTS) $(bartlby_cmd_DEPENDENCIES) 
	@rm -f bartlby_cmd$(EXEEXT)
	$(AM_V_CCLD)$(bartlby_cmd_LINK) $(bartlby_cmd_OBJECTS) $(bartlby_cmd_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/bartlby_agent-agent.Po
include ./$(DEPDIR)/bartlby_agent-config.Po
include ./$(DEPDIR)/bartlby_agent_v2-agent_v2.Po
include ./$(DEPDIR)/bartlby_agent_v2-config.Po
include ./$(DEPDIR)/bartlby_agent_v2-global.Po
include ./$(DEPDIR)/bartlby_cmd-cmd.Po
include ./$(DEPDIR)/bartlby_cmd-config.Po
include ./$(DEPDIR)/bartlby_cmd-global.Po

.c.o:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC) \
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c -o $@ $<

.c.obj:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC) \
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

bartlby_agent-config.o: config.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bartlby_agent_CFLAGS) $(CFLAGS) -MT bartlby_agent-config.o -MD -MP -MF $(DEPDIR)/bartlby_agent-config.Tpo -c -o bartlby_agent-config.o `test -f 'config.c' || echo '$(srcdir)/'`config.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/bartlby_agent-config.Tpo $(DEPDIR)/bartlby_agent-config.Po
#	$(AM_V_CC) \
#	source='config.c' object='bartlby_agent-config.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bartlby_agent_CFLAGS) $(CFLAGS) -c -o bartlby_agent-config.o `test -f 'config.c' || echo '$(srcdir)/'`config.c

bartlby_agent-config.obj: config.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bartlby_agent_CFLAGS) $(CFLAGS) -MT bartlby_agent-config.obj -MD -MP -MF $(DEPDIR)/bartlby_agent-config.Tpo -c -o bartlby_agent-config.obj `if test -f 'config.c'; then $(CYGPATH_W) 'config.c'; else $(CYGPATH_W) '$(srcdir)/config.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/bartlby_agent-config.Tpo $(DEPDIR)/bartlby_agent-config.Po
#	$(AM_V_CC) \
#	source='config.c' object='bartlby_agent-config.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bartlby_agent_CFLAGS) $(CFLAGS) -c -o bartlby_agent-config.obj `if test -f 'config.c'; then $(CYGPATH_W) 'config.c'; else $(CYGPATH_W) '$(srcdir)/config.c'; fi`

bartlby_agent-agent.o: agent.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bartlby_agent_CFLAGS) $(CFLAGS) -MT bartlby_agent-agent.o -MD -MP -MF $(DEPDIR)/bartlby_agent-agent.Tpo -c -o bartlby_agent-agent.o `test -f 'agent.c' || echo '$(srcdir)/'`agent.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/bartlby_agent-agent.Tpo $(DEPDIR)/bartlby_agent-agent.Po
#	$(AM_V_CC) \
#	source='agent.c' object='bartlby_agent-agent.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bartlby_agent_CFLAGS) $(CFLAGS) -c -o bartlby_agent-agent.o `test -f 'agent.c' || echo '$(srcdir)/'`agent.c

bartlby_agent-agent.obj: agent.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bartlby_agent_CFLAGS) $(CFLAGS) -MT bartlby_agent-agent.obj -MD -MP -MF $(DEPDIR)/bartlby_agent-agent.Tpo -c -o bartlby_agent-agent.obj `if test -f 'agent.c'; then $(CYGPATH_W) 'agent.c'; else $(CYGPATH_W) '$(srcdir)/agent.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/bartlby_agent-agent.Tpo $(DEPDIR)/bartlby_agent-agent.Po
#	$(AM_V_CC) \
#	source='agent.c' object='bartlby_agent-agent.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bartlby_agent_CFLAGS) $(CFLAGS) -c -o bartlby_agent-agent.obj `if test -f 'agent.c'; then $(CYGPATH_W) 'agent.c'; else $(CYGPATH_W) '$(srcdir)/agent.c'; fi`

bartlby_agent_v2-config.o: config.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bartlby_agent_v2_CFLAGS) $(CFLAGS) -MT bartlby_agent_v2-config.o -MD -MP -MF $(DEPDIR)/bartlby_agent_v2-config.Tpo -c -o bartlby_agent_v2-config.o `test -f 'config.c' || echo '$(srcdir)/'`config.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/bartlby_agent_v2-config.Tpo $(DEPDIR)/bartlby_agent_v2-config.Po
#	$(AM_V_CC) \
#	source='config.c' object='bartlby_agent_v2-config.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bartlby_agent_v2_CFLAGS) $(CFLAGS) -c -o bartlby_agent_v2-config.o `test -f 'config.c' || echo '$(srcdir)/'`config.c

bartlby_agent_v2-config.obj: config.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bartlby_agent_v2_CFLAGS) $(CFLAGS) -MT bartlby_agent_v2-config.obj -MD -MP -MF $(DEPDIR)/bartlby_agent_v2-config.Tpo -c -o bartlby_agent_v2-config.obj `if test -f 'config.c'; then $(CYGPATH_W) 'config.c'; else $(CYGPATH_W) '$(srcdir)/config.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/bartlby_agent_v2-config.Tpo $(DEPDIR)/bartlby_agent_v2-config.Po
#	$(AM_V_CC) \
#	source='config.c' object='bartlby_agent_v2-config.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bartlby_agent_v2_CFLAGS) $(CFLAGS) -c -o bartlby_agent_v2-config.obj `if test -f 'config.c'; then $(CYGPATH_W) 'config.c'; else $(CYGPATH_W) '$(srcdir)/config.c'; fi`

bartlby_agent_v2-agent_v2.o: agent_v2.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bartlby_agent_v2_CFLAGS) $(CFLAGS) -MT bartlby_agent_v2-agent_v2.o -MD -MP -MF $(DEPDIR)/bartlby_agent_v2-agent_v2.Tpo -c -o bartlby_agent_v2-agent_v2.o `test -f 'agent_v2.c' || echo '$(srcdir)/'`agent_v2.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/bartlby_agent_v2-agent_v2.Tpo $(DEPDIR)/bartlby_agent_v2-agent_v2.Po
#	$(AM_V_CC) \
#	source='agent_v2.c' object='bartlby_agent_v2-agent_v2.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bartlby_agent_v2_CFLAGS) $(CFLAGS) -c -o bartlby_agent_v2-agent_v2.o `test -f 'agent_v2.c' || echo '$(srcdir)/'`agent_v2.c

bartlby_agent_v2-agent_v2.obj: agent_v2.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bartlby_agent_v2_CFLAGS) $(CFLAGS) -MT bartlby_agent_v2-agent_v2.obj -MD -MP -MF $(DEPDIR)/bartlby_agent_v2-agent_v2.Tpo -c -o bartlby_agent_v2-agent_v2.obj `if test -f 'agent_v2.c'; then $(CYGPATH_W) 'agent_v2.c'; else $(CYGPATH_W) '$(srcdir)/agent_v2.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/bartlby_agent_v2-agent_v2.Tpo $(DEPDIR)/bartlby_agent_v2-agent_v2.Po
#	$(AM_V_CC) \
#	source='agent_v2.c' object='bartlby_agent_v2-agent_v2.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bartlby_agent_v2_CFLAGS) $(CFLAGS) -c -o bartlby_agent_v2-agent_v2.obj `if test -f 'agent_v2.c'; then $(CYGPATH_W) 'agent_v2.c'; else $(CYGPATH_W) '$(srcdir)/agent_v2.c'; fi`

bartlby_agent_v2-global.o: global.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bartlby_agent_v2_CFLAGS) $(CFLAGS) -MT bartlby_agent_v2-global.o -MD -MP -MF $(DEPDIR)/bartlby_agent_v2-global.Tpo -c -o bartlby_agent_v2-global.o `test -f 'global.c' || echo '$(srcdir)/'`global.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/bartlby_agent_v2-global.Tpo $(DEPDIR)/bartlby_agent_v2-global.Po
#	$(AM_V_CC) \
#	source='global.c' object='bartlby_agent_v2-global.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bartlby_agent_v2_CFLAGS) $(CFLAGS) -c -o bartlby_agent_v2-global.o `test -f 'global.c' || echo '$(srcdir)/'`global.c

bartlby_agent_v2-global.obj: global.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bartlby_agent_v2_CFLAGS) $(CFLAGS) -MT bartlby_agent_v2-global.obj -MD -MP -MF $(DEPDIR)/bartlby_agent_v2-global.Tpo -c -o bartlby_agent_v2-global.obj `if test -f 'global.c'; then $(CYGPATH_W) 'global.c'; else $(CYGPATH_W) '$(srcdir)/global.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/bartlby_agent_v2-global.Tpo $(DEPDIR)/bartlby_agent_v2-global.Po
#	$(AM_V_CC) \
#	source='global.c' object='bartlby_agent_v2-global.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bartlby_agent_v2_CFLAGS) $(CFLAGS) -c -o bartlby_agent_v2-global.obj `if test -f 'global.c'; then $(CYGPATH_W) 'global.c'; else $(CYGPATH_W) '$(srcdir)/global.c'; fi`

bartlby_cmd-config.o: config.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bartlby_cmd_CFLAGS) $(CFLAGS) -MT bartlby_cmd-config.o -MD -MP -MF $(DEPDIR)/bartlby_cmd-config.Tpo -c -o bartlby_cmd-config.o `test -f 'config.c' || echo '$(srcdir)/'`config.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/bartlby_cmd-config.Tpo $(DEPDIR)/bartlby_cmd-config.Po
#	$(AM_V_CC) \
#	source='config.c' object='bartlby_cmd-config.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bartlby_cmd_CFLAGS) $(CFLAGS) -c -o bartlby_cmd-config.o `test -f 'config.c' || echo '$(srcdir)/'`config.c

bartlby_cmd-config.obj: config.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bartlby_cmd_CFLAGS) $(CFLAGS) -MT bartlby_cmd-config.obj -MD -MP -MF $(DEPDIR)/bartlby_cmd-config.Tpo -c -o bartlby_cmd-config.obj `if test -f 'config.c'; then $(CYGPATH_W) 'config.c'; else $(CYGPATH_W) '$(srcdir)/config.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/bartlby_cmd-config.Tpo $(DEPDIR)/bartlby_cmd-config.Po
#	$(AM_V_CC) \
#	source='config.c' object='bartlby_cmd-config.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bartlby_cmd_CFLAGS) $(CFLAGS) -c -o bartlby_cmd-config.obj `if test -f 'config.c'; then $(CYGPATH_W) 'config.c'; else $(CYGPATH_W) '$(srcdir)/config.c'; fi`

bartlby_cmd-global.o: global.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bartlby_cmd_CFLAGS) $(CFLAGS) -MT bartlby_cmd-global.o -MD -MP -MF $(DEPDIR)/bartlby_cmd-global.Tpo -c -o bartlby_cmd-global.o `test -f 'global.c' || echo '$(srcdir)/'`global.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/bartlby_cmd-global.Tpo $(DEPDIR)/bartlby_cmd-global.Po
#	$(AM_V_CC) \
#	source='global.c' object='bartlby_cmd-global.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bartlby_cmd_CFLAGS) $(CFLAGS) -c -o bartlby_cmd-global.o `test -f 'global.c' || echo '$(srcdir)/'`global.c

bartlby_cmd-global.obj: global.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bartlby_cmd_CFLAGS) $(CFLAGS) -MT bartlby_cmd-global.obj -MD -MP -MF $(DEPDIR)/bartlby_cmd-global.Tpo -c -o bartlby_cmd-global.obj `if test -f 'global.c'; then $(CYGPATH_W) 'global.c'; else $(CYGPATH_W) '$(srcdir)/global.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/bartlby_cmd-global.Tpo $(DEPDIR)/bartlby_cmd-global.Po
#	$(AM_V_CC) \
#	source='global.c' object='bartlby_cmd-global.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bartlby_cmd_CFLAGS) $(CFLAGS) -c -o bartlby_cmd-global.obj `if test -f 'global.c'; then $(CYGPATH_W) 'global.c'; else $(CYGPATH_W) '$(srcdir)/global.c'; fi`

bartlby_cmd-cmd.o: cmd.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bartlby_cmd_CFLAGS) $(CFLAGS) -MT bartlby_cmd-cmd.o -MD -MP -MF $(DEPDIR)/bartlby_cmd-cmd.Tpo -c -o bartlby_cmd-cmd.o `test -f 'cmd.c' || echo '$(srcdir)/'`cmd.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/bartlby_cmd-cmd.Tpo $(DEPDIR)/bartlby_cmd-cmd.Po
#	$(AM_V_CC) \
#	source='cmd.c' object='bartlby_cmd-cmd.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bartlby_cmd_CFLAGS) $(CFLAGS) -c -o bartlby_cmd-cmd.o `test -f 'cmd.c' || echo '$(srcdir)/'`cmd.c

bartlby_cmd-cmd.obj: cmd.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bartlby_cmd_CFLAGS) $(CFLAGS) -MT bartlby_cmd-cmd.obj -MD -MP -MF $(DEPDIR)/bartlby_cmd-cmd.Tpo -c -o bartlby_cmd-cmd.obj `if test -f 'cmd.c'; then $(CYGPATH_W) 'cmd.c'; else $(CYGPATH_W) '$(srcdir)/cmd.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/bartlby_cmd-cmd.Tpo $(DEPDIR)/bartlby_cmd-cmd.Po
#	$(AM_V_CC) \
#	source='cmd.c' object='bartlby_cmd-cmd.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(bartlby_cmd_CFLAGS) $(CFLAGS) -c -o bartlby_cmd-cmd.obj `if test -f 'cmd.c'; then $(CYGPATH_W) 'cmd.c'; else $(CYGPATH_W) '$(srcdir)/cmd.c'; fi`
install-dist_mysqlDATA: $(dist_mysql_DATA)
	@$(NORMAL_INSTALL)
	test -z "$(mysqldir)" || $(MKDIR_P) "$(DESTDIR)$(mysqldir)"
	@list='$(dist_mysql_DATA)'; test -n "$(mysqldir)" || list=; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(mysqldir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(mysqldir)" || exit $$?; \
	done

uninstall-dist_mysqlDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(dist_mysql_DATA)'; test -n "$(mysqldir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	test -n "$$files" || exit 0; \
	echo " ( cd '$(DESTDIR)$(mysqldir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(mysqldir)" && rm -f $$files

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	set x; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | bzip2 -9 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-lzma: distdir
	tardir=$(distdir) && $(am__tar) | lzma -9 -c >$(distdir).tar.lzma
	$(am__remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | xz -c >$(distdir).tar.xz
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lzma*) \
	  lzma -dc $(distdir).tar.lzma | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod u+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@$(am__cd) '$(distuninstallcheck_dir)' \
	&& test `$(distuninstallcheck_listfiles) | wc -l` -le 1 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile $(PROGRAMS) $(SCRIPTS) $(DATA) config.h
installdirs:
	for dir in "$(DESTDIR)$(mysqldir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-generic clean-noinstPROGRAMS mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am: install-dist_mysqlDATA
	@$(NORMAL_INSTALL)
	$(MAKE) $(AM_MAKEFLAGS) install-data-hook
install-dvi: install-dvi-am

install-dvi-am:

install-exec-am:

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-dist_mysqlDATA

.MAKE: all install-am install-data-am install-strip

.PHONY: CTAGS GTAGS all all-am am--refresh check check-am clean \
	clean-generic clean-noinstPROGRAMS ctags dist dist-all \
	dist-bzip2 dist-gzip dist-lzma dist-shar dist-tarZ dist-xz \
	dist-zip distcheck distclean distclean-compile \
	distclean-generic distclean-hdr distclean-tags distcleancheck \
	distdir distuninstallcheck dvi dvi-am html html-am info \
	info-am install install-am install-data install-data-am \
	install-data-hook install-dist_mysqlDATA install-dvi \
	install-dvi-am install-exec install-exec-am install-html \
	install-html-am install-info install-info-am install-man \
	install-pdf install-pdf-am install-ps install-ps-am \
	install-strip installcheck installcheck-am installdirs \
	maintainer-clean maintainer-clean-generic mostlyclean \
	mostlyclean-compile mostlyclean-generic pdf pdf-am ps ps-am \
	tags uninstall uninstall-am uninstall-dist_mysqlDATA


install-data-hook:
	chmod +x  $(DESTDIR)$(prefix)/bartlby_agent
	chmod +x  $(DESTDIR)$(prefix)/bartlby_agent_v2
	chmod +x  $(DESTDIR)$(prefix)/bartlby_cmd

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
