Document: bartlby-agent
Title: Debian bartlby-agent Manual
Author: <insert document author here>
Abstract: This manual describes what bartlby-agent is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/bartlby-agent/bartlby-agent.sgml.gz

Format: postscript
Files: /usr/share/doc/bartlby-agent/bartlby-agent.ps.gz

Format: text
Files: /usr/share/doc/bartlby-agent/bartlby-agent.text.gz

Format: HTML
Index: /usr/share/doc/bartlby-agent/html/index.html
Files: /usr/share/doc/bartlby-agent/html/*.html
